AWSTemplateFormatVersion: '2010-09-09'
Description: Shop configuration table
Resources:
  shopConfigs:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  TableName:
    Value: !Ref 'shopConfigs'
    Description: Shop configuration table